# Generated by Django 4.0.3 on 2022-03-12 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_type', models.CharField(choices=[('singer', 'singer'), ('musician', 'musician'), ('painter', 'painter'), ('dancer', 'dancer')], max_length=100)),
                ('artist_name', models.CharField(choices=[('Michael Jackson', 'Michael Jackson'), ('Arijit Singh', 'Arijit Singh'), ('Justin Bieber', 'Justin Bieber'), ('Guru Randhava', 'Guru Randhava'), ('Zakir Hussain', 'Zakir Hussain'), ('Amjad Ali Khan', 'Amjad Ali Khan'), ('Shipla Gupta', 'Shipla Gupta'), ('Paresh Maity', 'Paresh Maity'), ('Parbhu Deva', 'Parbhu Deva')], max_length=100)),
                ('artist_desc', models.TextField()),
                ('artist_image', models.ImageField(upload_to='artist_image/')),
                ('artist_performance_desc', models.TextField()),
                ('artist_performance_image', models.ImageField(upload_to='artist_performance_image/')),
                ('artist_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
