# Generated by Django 4.0.3 on 2022-03-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='artist_performance_desc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='artist_performance_image',
        ),
        migrations.AlterField(
            model_name='profile',
            name='artist_type',
            field=models.CharField(choices=[('Singer', 'Singer'), ('Musician', 'Musician'), ('Painter', 'Painter'), ('Dancer', 'Dancer')], max_length=100),
        ),
    ]
