# Generated by Django 4.0.3 on 2022-03-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_profile_artist_type_book_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_artist',
            name='artist_name',
        ),
        migrations.RemoveField(
            model_name='book_artist',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='book_artist',
            name='event_end_time',
        ),
        migrations.RemoveField(
            model_name='book_artist',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='book_artist',
            name='event_start_time',
        ),
        migrations.RemoveField(
            model_name='book_artist',
            name='event_venue',
        ),
        migrations.RemoveField(
            model_name='book_artist',
            name='remarks',
        ),
    ]
