# Generated by Django 4.0.3 on 2022-03-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_book_artist_artist_name_book_artist_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_artist',
            name='artist_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
