# Generated by Django 4.0.3 on 2022-04-01 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_book_artist_artist_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_artist',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
