# Generated by Django 4.0.3 on 2022-04-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_book_artist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='artist_price',
            field=models.CharField(default='Rs.10000', max_length=100),
        ),
    ]
