# Generated by Django 4.0.3 on 2022-04-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_profile_artist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='artist_price',
            field=models.CharField(max_length=100),
        ),
    ]
