# Generated by Django 4.0.3 on 2022-04-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_profile_artist_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_artist',
            name='payment_status',
            field=models.CharField(default='Not Paid', max_length=100),
        ),
    ]
